# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.CharField(blank=True, max_length=4000)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='reviews.Review')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'db_table': 'articles',
            },
        ),
    ]
