# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('criteria_type', models.PositiveSmallIntegerField(choices=[(1, 'inclusion criteria'), (2, 'exclusion criteria')], default=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion', to='reviews.Review')),
            ],
            options={
                'verbose_name': 'criteria',
                'verbose_name_plural': 'criterion',
                'db_table': 'criterion',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'db_table': 'keywords',
            },
        ),
    ]
