# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_criteria_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
