# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171113_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='review',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
    ]
