# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20171113_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('criterion_type', models.PositiveSmallIntegerField(choices=[(1, 'inclusion criteria'), (2, 'exclusion criteria')], default=1)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='reviews.Review')),
            ],
            options={
                'verbose_name': 'criterion',
                'verbose_name_plural': 'criteria',
                'db_table': 'criteria',
            },
        ),
    ]
