# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_criterion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Criterion',
            new_name='Criteria',
        ),
        migrations.AlterModelOptions(
            name='criteria',
            options={'verbose_name': 'criteria', 'verbose_name_plural': 'criteria'},
        ),
        migrations.RenameField(
            model_name='criteria',
            old_name='criterion_type',
            new_name='criteria_type',
        ),
    ]
